
insert into magazzini(indirizzo, sedeAppartenenza) values("ITALY, Venezia, 30122, Castello 5490", 1);
insert into magazzini(indirizzo, sedeAppartenenza) values("ITALY, Mestre, 30174, Piazza Erminio Ferretto 13", 2);
insert into magazzini(indirizzo, sedeAppartenenza) values("ITALY, Padova, 35122, Via VIII Febbraio 15", 3);
insert into magazzini(indirizzo, sedeAppartenenza) values("ITALY, Milano, 20121, Corso Vittorio Emanuele II 12", 4);
insert into magazzini(indirizzo, sedeAppartenenza) values("ITALY, Roma, 00187, Via Flavia 2", 5);
insert into magazzini(indirizzo, sedeAppartenenza) values("ITALY, Firenze, 50144, Piazza di S. Jacopino 30", 6);
insert into magazzini(indirizzo, sedeAppartenenza) values("ITALY, Torino, 10128, Corso Castelfidardo 7", 7);
insert into magazzini(indirizzo, sedeAppartenenza) values("FRANCE, Paris, 75002 , 24 Rue Saint-Augustin", 8);
insert into magazzini(indirizzo, sedeAppartenenza) values("SPAIN, Madrid, 28004, Plaza de Carlos Cambronero 4", 9);
insert into magazzini(indirizzo, sedeAppartenenza) values("GERMANY, Berlin, 10117, Franzosische Strasse 24", 10);
insert into magazzini(indirizzo, sedeAppartenenza) values("PORTUGAL, Lisboa, 1150-175, R. Gomes Freire 60", 11);
insert into magazzini(indirizzo, sedeAppartenenza) values("POLAND, Wroclaw, 50-113, OdrzaNska 17", 12);
insert into magazzini(indirizzo, sedeAppartenenza) values("UK, Belfast, BT2 7BA, 46 Great Victoria St", 13);
insert into magazzini(indirizzo, sedeAppartenenza) values("UK, London, W1S 2XG, 9 Conduit St", 14);
insert into magazzini(indirizzo, sedeAppartenenza) values("USA, New York, MY 10016, 181 Lexington Ave", 15);
insert into magazzini(indirizzo, sedeAppartenenza) values("USA, Miami Beach, FL 33139, 1427 West Ave", 16);
insert into magazzini(indirizzo, sedeAppartenenza) values("USA, Long Beach, CA 90802, 435 Shoreline Village Drive", 17);
insert into magazzini(indirizzo, sedeAppartenenza) values("USA, Houston, TX 77003, 1701 Webster St E2", 18);
insert into magazzini(indirizzo, sedeAppartenenza) values("BULGARIA, Sofia, 1000 , ul. Hristo Belchev 42", 19);
insert into magazzini(indirizzo, sedeAppartenenza) values("LITHUANIA, Vilnius, 01123, Pilies g. 16", 20);
insert into magazzini(indirizzo, sedeAppartenenza) values("AUSTRIA, Wien, 1010, Herrengasse 14", 21);
