insert into merci(codice, nome, tipo) values("9980120", "ZUCCHERO SEMOLATO PACCO 10 X 1 KG PZ 1XKG10", "alimento");
insert into merci(codice, nome, tipo) values("9509723", "UOVO TUORLO PASTOR. SFOGLIA GIALLA PZ12XKG1", "bevanda");
insert into merci(codice, nome, tipo) values("9981426", "UOVA GRANDI PASTA GIALLA 90 PZ PZ 1XPZ1", "alimento");
insert into merci(codice, nome, tipo) values("9981402", "UOVA MEDIO-GRANDI PASTA GIALLA 90PZ PZ 1XPZ1", "alimento");
insert into merci(codice, nome, tipo) values("9971035", "BOBINA DOPPIO VELO 2 ROTOLI PZ 1XPZ1", "alimento");
insert into merci(codice, nome, tipo) values("9971001", "ROTOLO CARTAFORNO MT 50 PZ 9XPZ1", "alimento");
insert into merci(codice, nome, tipo) values("9971023", "ROTOLO PELLICOLA PVC MT 300 CM 33 PZ 9XPZ1", "bevanda");
insert into merci(codice, nome, tipo) values("9971067", "SAC A POCHE ROTOLO 72 PZ PZ 5XPZ1", "bevanda");
insert into merci(codice, nome, tipo) values("9971072", "SALVIETTE DETERGENTI NATURA'S 500 PZ PZ 1XPZ1", "alimento");
insert into merci(codice, nome, tipo) values("3180835", "MORTADELLA 1/2 C/PISTACCHI VILLANI PZ 1XKG7,1", "alimento");
insert into merci(codice, nome, tipo) values("3180950", "PANCETTA AFF. STUFATA 1/2 EXTRA PZ 1XKG4,8", "alimento");
insert into merci(codice, nome, tipo) values("3181816", "PROSC. CRUDO S/O MEC ADDOBBO PZ 1XKG6,7", "bevanda");
insert into merci(codice, nome, tipo) values("3182531", "SALAME LV PZ 1XKG0,8", "bevanda");
insert into merci(codice, nome, tipo) values("3183527", "SALSICCIA IN PASTA TASTAS.PROSUS 1 KG PZ 6 X KG 1,0", "bevanda");
insert into merci(codice, nome, tipo) values("3181018", "SPALLA COTTA SGRASSATA PZ 2XKG6,7", "bevanda");
insert into merci(codice, nome, tipo) values("3152543", "WURSTEL GUSTO DECISO POLLO/TACCHINO PZ12XPZ1", "bevanda");
insert into merci(codice, nome, tipo) values("7204064", "TORTA PROFITEROL CIOCC. VASCH.KG 1.3 PZ 1XPZ1", "bevanda");
insert into merci(codice, nome, tipo) values("9981005", "BARBABIETOLE ROSSE (RAPE) 3 X 2.6 KG PZ 3 X PZ 1", "alimento");
insert into merci(codice, nome, tipo) values("9980637", "CAPPERI AL SALE KG 1 PZ 6XPZ1", "bevanda");
insert into merci(codice, nome, tipo) values("9980652", "CARCIOFI FETTINE NAT. BUSTA 1700GR PZ12XPZ1", "alimento");
insert into merci(codice, nome, tipo) values("9980754", "FUNGHI CHAMPIGNON TRIF. NATURA'S KG 1.7 PZ12XPZ1", "bevanda");
insert into merci(codice, nome, tipo) values("9980360", "OLIVE NERE DENOC. BUSTA BONETTO 3.8 KG PZ 4XPZ1", "alimento");
insert into merci(codice, nome, tipo) values("9980629", "OLIVE VERDI GIGANTI VASO 1.6KG NOVELLA PZ 6XPZ1", "alimento");
insert into merci(codice, nome, tipo) values("1023010", "CARCIOFI CUORI EST PZ10XKG1", "bevanda");
insert into merci(codice, nome, tipo) values("1024340", "FAGIOLINI FINI EST EXTRA PZ 4XKG2,5", "bevanda");
insert into merci(codice, nome, tipo) values("1026640", "PATATE PREFR. PRIMPOM LUTOSA PZ 4XKG2,5", "bevanda");
insert into merci(codice, nome, tipo) values("1017535", "PISELLI FINI EXTRA PZ 4XKG2,5", "alimento");
insert into merci(codice, nome, tipo) values("1028027", "SPINACI CUBO GR 50 ESTERO PZ 4XKG2,5", "bevanda");
insert into merci(codice, nome, tipo) values("GELA08", "FAGIOLINI FINISSIMI 8/9MM KG 2.5 GELAGRI cf 4", "bevanda");
insert into merci(codice, nome, tipo) values("AGRA01", "PATATE FRITTE 9 MM AGRARFR PROFESSIONAL cf 4", "alimento");
insert into merci(codice, nome, tipo) values("GELA14", "PISELLI FINI KG 2.5 MESTRO DI VERD. Cf 4", "alimento");
insert into merci(codice, nome, tipo) values("GELA07", "SPINACI PORZ. 50GR KG 2.5 MAESTRO DI VER cf 4", "alimento");
insert into merci(codice, nome, tipo) values("GEA001", "PASTA PER LASAGNE PREC. 12F 5X2 ANT.LAB KG 2.5 cf 5", "bevanda");
insert into merci(codice, nome, tipo) values("GEL064", "ANELLI CALAMARO ALT 10 % ALFRIO 2 X 2.5K KG 1 cf 2", "alimento");
insert into merci(codice, nome, tipo) values("STA004", "BRANZINI 300/400 EVISC. 20% 5KG IQF CONG KG 1 cf 1", "bevanda");
insert into merci(codice, nome, tipo) values("BRAS23", "CALAMARI CIUFFI BRASMAR 40/60 GR750 cf 10", "alimento");
insert into merci(codice, nome, tipo) values("EFF078", "EFF078 CALAMARI PUL. THAI U/10 30% CT 2,270 cf 4", "alimento");
insert into merci(codice, nome, tipo) values("EFF095", "CALAMARI SPORCHI C4 PATAG C. KG 1 cf 1", "alimento");
insert into merci(codice, nome, tipo) values("PES007", "CALAMARI SPORCHI C4L PATAG (12-15)C. KG 1 cf 1", "alimento");
insert into merci(codice, nome, tipo) values("ATL011", "CALAMARI TAGLIATI PUL20/40 C/P IQF INDIA KG 1 cf 10", "bevanda");
insert into merci(codice, nome, tipo) values("EFF042", "FILETTI DI PANGASIO 170/220 20% C. KG 1 cf 10", "alimento");
insert into merci(codice, nome, tipo) values("STA014", "FILETTO BRANZINO 120-160 25% 5KG C/P IQF cf 1", "bevanda");
insert into merci(codice, nome, tipo) values("ROY006", "GAMBERI GOBETTI CRUDI 160-200 IQF ROYAL KG 1 cf 1", "alimento");
insert into merci(codice, nome, tipo) values("NEW038", "MAZZANCOLLE SGUSC.31/40 DEV25%IQF KG 1 cf 10", "alimento");
insert into merci(codice, nome, tipo) values("EFF016", "POLPO PULITO 2000/3000 10 % INDOP. KG 1 cf 1", "alimento");
insert into merci(codice, nome, tipo) values("MED001", "SALMONE FILETTO 800/1000 IQF 10%NORVEGIA KG 1 cf 10", "bevanda");
insert into merci(codice, nome, tipo) values("COMA02", "SEPPIE PUL 13/20 IQF 20% INDIA SAGAR C. KG 1 cf 1", "alimento");
insert into merci(codice, nome, tipo) values("BRAS17", "VONGOLE SGUSC 700/1000 BORSA GR800 BRASM KG 1 cf 10", "alimento");
insert into merci(codice, nome, tipo) values("DI0013", "BOVINO MACINATO ORO IQF 1KG C. cf 5", "bevanda");
insert into merci(codice, nome, tipo) values("EST001", "POLLO COSCETTE CF X 7 CONG KG 3 cf 1", "bevanda");
insert into merci(codice, nome, tipo) values("BAL034", "SUINO FILONE SPAGNA C. KG 4 cf 3", "bevanda");
insert into merci(codice, nome, tipo) values("RUB027", "SUINO STINCO TAGLIATO A 1/2 C GR 250 cf 30", "alimento");
insert into merci(codice, nome, tipo) values("ROSA02", "VITELLO ROTOLO PETTO SV GELO CT 1 cf 8", "bevanda");
insert into merci(codice, nome, tipo) values("ROSA39", "VITELLO ROTOLO REALE SV GELO CT 1 cf 8", "bevanda");
insert into merci(codice, nome, tipo) values("ASC301", "VITELLO SPALLA INTERA NL S/OSSO C. EKRO CT 1 cf 6", "bevanda");
insert into merci(codice, nome, tipo) values("RUB058", "BACCALA' MANTECATO ATM KG.1 PZ 1 cf 2", "alimento");
insert into merci(codice, nome, tipo) values("STU027", "MASCARPONE GR. 500 STUFFER PZ 1 cf 6", "alimento");
insert into merci(codice, nome, tipo) values("CEP028", "MOZZARELLA 100GR CAMMINO D'ORO KG 1 cf 1", "alimento");
insert into merci(codice, nome, tipo) values("CEP019", "MOZZARELLA FILONE KG.1 CAMMINO D'ORO PZ 1 cf 15", "bevanda");
insert into merci(codice, nome, tipo) values("GRAN41", "LATTE PS UHT LT 1 GRAND MID GRANAROLO PZ 1 cf 12", "bevanda");
insert into merci(codice, nome, tipo) values("FIO006", "MORTADELLA IMPERIALE KG 6 FIORUCCI KG 6 cf 2", "alimento");
insert into merci(codice, nome, tipo) values("COA009", "PANCETTA STUFATA 1/2 AFFUM. COATI KG 1,5 cf 8", "bevanda");
insert into merci(codice, nome, tipo) values("COA006", "PROSC. COTTO MISTER PIZZA COATI KG 2,5 cf 2", "alimento");
insert into merci(codice, nome, tipo) values("SFR004", "PROSC.CRUDO S/O MEC STAG ADDOBBO KG 6 cf 3", "alimento");
insert into merci(codice, nome, tipo) values("MAR004", "PROSC.CRUDO S/O PARMA 15/16 M PRESS KG 6 cf 1", "bevanda");
insert into merci(codice, nome, tipo) values("COA010", "SALAMINO PICCANTE DRITTO COATI KG 7,5 cf 12", "bevanda");
insert into merci(codice, nome, tipo) values("ALF001", "BRODO VEGETALE S/GLUTAM.KG 1 LUNA ILDIA Pz 1 cf 12", "alimento");
insert into merci(codice, nome, tipo) values("CDM002", "CARCIOFI SPICCHI BS KG1,7 CA DE LA MARCA PZ 1 cf 1o", "bevanda");
insert into merci(codice, nome, tipo) values("NOV003", "FUNGHI CHAMPIGNON TRIF 1.7KG BS COMPAR PZ 1 cf 6", "alimento");
insert into merci(codice, nome, tipo) values("GENF10", " KETCHUP BS 12GRX100 TOP FOOD CT 1 cf 100", "alimento");
insert into merci(codice, nome, tipo) values("GENF11", " MAIONESE BS 12GRX100 TOP FOOD CT 1 cf 100", "alimento");
insert into merci(codice, nome, tipo) values("GENF02", "MAIONESE SQEEZER TOP ML 1000 PZ 1 cf 12", "bevanda");
insert into merci(codice, nome, tipo) values("NOV008", "OLIVE NERE S/O SAL. VS ML 2020 NOVA KG 1,700 cf 6", "alimento");
insert into merci(codice, nome, tipo) values("ALF019", "PEPE NERO POLVERE GR 320 ILDIA GR 130 f 6", "alimento");
insert into merci(codice, nome, tipo) values("STERI1", "POLPA POMODORO 10 KG SOLE MIO PZ 3 cf 1", "alimento");
insert into merci(codice, nome, tipo) values("TOR001", "POMODORI PELATI 2550G INT SMALT BELPOMOPZ 3 cf 6", "bevanda");
insert into merci(codice, nome, tipo) values("CIS002", "SALE IODATO FINO KG 1 GEMMA cf 12", "alimento");
insert into merci(codice, nome, tipo) values("CIS001", "SALE IODATO GROSSO KG 1 GEMMA cf 12", "alimento");
insert into merci(codice, nome, tipo) values("SID042", "SALE ROSA HYMALAYA GR 450 PET SIDEA cf 6", "bevanda");
insert into merci(codice, nome, tipo) values("AMAT02", "TONNO O/G 1 KG BS AMATI PZ 1 cf 8", "alimento");
insert into merci(codice, nome, tipo) values("UNIG02", "PANNA VEGETALE DA CUCINA 500ML MF PZ 1 cf 20", "alimento");
insert into merci(codice, nome, tipo) values("UNIG08", "PANNA VEGETETALE DA MONT. L1 GOLD PZ 1 cf 12", "bevanda");
insert into merci(codice, nome, tipo) values("ARE003", "ACETO BIANCO 500ML 6,1 % CHIANTIGIANO PZ 1 cf 12", "bevanda");
insert into merci(codice, nome, tipo) values("LEV001", "OLIO EXTRAV. LT.1 LA MASSERIA PZ 1 cf 12", "alimento");
insert into merci(codice, nome, tipo) values("LEV010", "OLIO EXTRAV. ML.500 LA MASSERIA PZ 1 cf 12", "bevanda");
insert into merci(codice, nome, tipo) values("UNIG06", "OLIO PALMA LT.10 FRAZ. FRIGGITUTTO PZ 1 cf 1", "bevanda");
insert into merci(codice, nome, tipo) values("GRA034", "GRANAROLO FETTUCCINE UOVO 124 KG 5 CT 1 cf 1", "alimento");
insert into merci(codice, nome, tipo) values("GRAZ04", "RISO CARNAROLI 5 KG GRAZIA PZ 1 cf 4", "bevanda");
insert into merci(codice, nome, tipo) values("SPI014", "SPIGADORO FUSILLI SEM 3 KG KG 3 cf 4", "bevanda");
insert into merci(codice, nome, tipo) values("SPI013", "SPIGADORO PENNINE RIG SEM 3 KG cf 4", "bevanda");
insert into merci(codice, nome, tipo) values("SPI020", "SPIGADORO SPAGHETTI SEM 3 KG cf 4", "bevanda");
insert into merci(codice, nome, tipo) values("FIE026", "BISCOTTI SAVOIARDI GR.400X12 GANDOVO cf 12", "alimento");
insert into merci(codice, nome, tipo) values("GENF04", "TOPPING CARAMELLO KG1 TOPPKING cf 6", "alimento");
insert into merci(codice, nome, tipo) values("GENF05", "TOPPING CIOCCOLATO KG1 TOPPKING cf 6", "alimento");
insert into merci(codice, nome, tipo) values("GENF17", "TOPPING FRAGOLA KG1 TOPPKING cf 6", "alimento");
insert into merci(codice, nome, tipo) values("CONT02", "PELLICOLA PVC 300 CONTITAL MT300 NUDO PZ 1 cf 9", "alimento");
insert into merci(codice, nome, tipo) values("ITAL03", "DET. BRILLANTANTE KG5 MATRIX PZ 1 cf 2", "bevanda");
insert into merci(codice, nome, tipo) values("ITAL04", "DET. PAVIMENTI LAVANDA SELV.KG5 MATRIX PZ 1 cf 2", "bevanda");
insert into merci(codice, nome, tipo) values("HYG031", "BOBINA 800STR PURA CELLULOSA 2 V PZ 1 cf 2", "bevanda");
insert into merci(codice, nome, tipo) values("HYG001", "SACCHI NERI 90 X 120 GR 150 MY 80 KG 1 cf 1", "bevanda");
